# Generated by Django 5.2.8 on 2025-11-15 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "platform_id",
                    models.CharField(
                        choices=[
                            ("WEB", "Web"),
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                        ],
                        default="WEB",
                        max_length=16,
                    ),
                ),
                ("ua_family", models.CharField(blank=True, max_length=128)),
                ("ip_masked", models.GenericIPAddressField(blank=True, null=True)),
                ("trusted", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("WEB", "Web"),
                            ("MOBILE", "Mobile"),
                            ("OPENID", "OIDC"),
                        ],
                        default="WEB",
                        max_length=16,
                    ),
                ),
                ("server_session_key", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="session_guard.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["user", "last_seen"], name="session_gua_user_id_2398d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["trusted"], name="session_gua_trusted_fcf8c8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="device",
            unique_together={("user", "device_id")},
        ),
        migrations.AddIndex(
            model_name="devicesession",
            index=models.Index(
                fields=["user", "session_type", "is_active"],
                name="session_gua_user_id_5275c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicesession",
            index=models.Index(
                fields=["device", "is_active"], name="session_gua_device__2f9939_idx"
            ),
        ),
    ]
